### ISSUE TITLE
Adopt Raynes/fs

### ISSUE THREAD

**Issue by jwhitlark** [clj-commons/wishlist#1]
https://github.com/Raynes/fs

**Comment by slipset** [comment]
Done :)

**Comment by martinklepsch** [comment]
@slipset Users can't open issues against https://github.com/clj-commons/fs

Also consider not forking a repo using GitHubs fork feature in the future. In my experience that has always caused trouble when the intention was to establish a new canonical location.

**Comment by slipset** [comment]
Issues should be enabled now. As for the forking, in this very case, as Raynes has passed away, there is no one with access to the original repo, and thus it’s not possible to transfer the repo. 

Erik. 
-- 
i farta

**Comment by martinklepsch** [comment]
@slipset Thanks. While a transfer is the best option you can also just push a repo to a GitHub remote (not using GitHub's Fork button) and the "forked from" subtitle will be gone. I think for a new canonical repository this would be desirable.

**Comment by danielcompton** [comment]
I've just re-pushed this as a canonical repository. As a side note, what is the lineage of this version fs? It has akvo/fs as the group ID, was that where this was forked from?

**Comment by slipset** [comment]
It was transferred from akvo, yes.
