### ISSUE TITLE
vizdeps

### ISSUE THREAD

**Issue by codeasone** [clj-commons/wishlist#11]
https://github.com/walmartlabs/vizdeps isn't getting enough love. 

Usage of this tooling is presently limited to lein `2.7.1` and [simple PRs](https://github.com/walmartlabs/vizdeps/pull/12) to address this are presently being ignored.

**Comment by danielcompton** [comment]
When the existing maintainers are still around, I'm a little bit hesitant to fork like this, especially when there are somewhat recent commits. If they would like to transfer maintenance over to CLJ Commons then that would be great, but I'd like to talk to them first to get their thoughts.

Forking a project is at some level a slightly aggressive act, so we shouldn't do it lightly.

**Comment by codeasone** [comment]
Hi @danielcompton, of course I understand and agree.

**Comment by cnuernber** [comment]
We have found this project to be crucial when you have a very large system with, for instance, a ton of apache dependencies and something doesn't work.


My vote would be to wait 1 week.  If a discussion ensues then we move forward that way and if no discussion ensues then we hard-fork and put proper attribution in the readme.  I would be happy to help (or 'just do it') bring this one completely up to date w/r/t leiningen and openjdk-11.

**Comment by hlship** [comment]
I have no problems whatsoever. I haven’t had any spare cycles for vizdeps and it could certainly use some TLC ... and I would have no problem contributing to the new project or redirecting people from the old. 

In terms of PRs ... that's on me, not having good notifications set up.  

But, yes, fork away.

**Comment by hlship** [comment]
... I was just about to merge those PRs and found out that the Open Source team at Walmart has removed my privs on vizdeps, so I can't do anything until they fix that.

**Comment by danielcompton** [comment]
This is now available at https://github.com/clj-commons/vizdeps.

**Comment by hlship** [comment]
The loss of access is a temporary oversight, rather than a more serious policy issue. Regardless, I’m on board with the fork.
