### ISSUE TITLE
Conch

### ISSUE THREAD

**Issue by charignon** [clj-commons/wishlist#15]
https://github.com/Raynes/conch is unfortunately unmaintained, see [this issue](https://github.com/Raynes/conch/pull/45) for context 😢.
The most up to date fork seems to be https://github.com/damiencollard/conch.
Could you let me know how I can help to migrate it under `clj-commons`?

@damiencollard, @jafingerhut, @grinderrz : FYI

**Comment by slipset** [comment]
@danielcompton would you like to try to transfer Raynes original version via Github, or should we seek to transfer/fork @damiencollard's version?

**Comment by damiencollard** [comment]
@charignon @slipset I haven't used Clojure in a long while and have no interest in conch anymore... You're of course welcome to fork my version.

**Comment by slipset** [comment]
Hi @damiencollard, 

I've added you as a member to clj-commons, so you should be able to transfer conch to us.
Let me know if you encounter any problems

**Comment by arnaudbos** [comment]
I think this can be closed now.

**Comment by slipset** [comment]
@arnaudbos Thank you not mentioning, I didn’t get a github notifiers for this.

**Comment by arnaudbos** [comment]
I'd be happy to help with the maintenance of conch. I'm not using it myself but so maybe other people would have more incentive to do that and contribute more regularly.

That being said, I'd like to play with the whole `Thread#start` and `future` thing and see what could be done to eat-up fewer resources.

At the very least I'd like to help put clj-commons/conch onto Clojars, link CircleCI builds and have cljdoc generated, which is the intent of my last PR.
