### ISSUE TITLE
Pushy

### ISSUE THREAD

**Issue by shen-tian** [clj-commons/wishlist#16]
Small but useful lib for hashless frontend routing with HTML5 pushstates.

https://github.com/kibu-australia/pushy

Seems abandoned. I've forked and made a new release here: https://github.com/lifecheq/pushy

- Fixes it for IE11
- Handles query params

I'm happy to maintain, but would prefer to do it under clj-commons if possible.

**Comment by danielcompton** [comment]
Pushy seems to be fairly [well used](https://clojars.org/kibu/pushy). I see you've already raised the idea of taking over maintenance at https://github.com/kibu-australia/pushy/issues/39. Before transferring your fork into clj-commons, I'll send an email to @wavejumper to see if he is interested in transferring the original. Thanks!

**Comment by shen-tian** [comment]
Hey. All quiet on the email front... next steps?

**Comment by dijonkitchen** [comment]
Looks like it's transferred: https://github.com/clj-commons/pushy 

Shall this issue be closed?

**Comment by danielcompton** [comment]
Yep!
