### ISSUE TITLE
Public keys used to sign cli-commons packages not found in public keyservers

### ISSUE THREAD

**Issue by manid** [clj-commons/wishlist#19]
Currently when trying to pgp-verify clj-commons/secretary I can't seem to find the public key used to sign this package (eg. from  pgp.mit.edu). Could these keys be uploaded or could you point a path where they might be.

**Comment by danielcompton** [comment]
@slipset I think you published the secretary release?

**Comment by danielcompton** [comment]
@manid what is the key fingerprint you found?

**Comment by manid** [comment]
For the 1.2.4 version of clj-commons/secretary the fingerprint is: 0x5ECFCC77F1E76BCD

**Comment by slipset** [comment]
Seems to correspond with my key.

**Comment by manid** [comment]
Looks like the key is now available: http://pool.sks-keyservers.net/pks/lookup?search=0x5ECFCC77F1E76BCD&op=vindex

**Comment by manid** [comment]
Thank you very much!

**Comment by slipset** [comment]
Thank you for reporting. Have a great week @manid!
