### ISSUE TITLE
spyscope

### ISSUE THREAD

**Issue by slipset** [clj-commons/wishlist#20]
https://github.com/dgrnbrg/spyscope/issues/26
So the question is if @randomizedthinking or @dgrnbrg would be willing to transfer the project?

**Comment by dgrnbrg** [comment]
I would be open to this. What does it take?

**Comment by slipset** [comment]
Doesn't take much. You transfer the repo to clj-commons, we maintain it.
If you also add clj-commons to the group that owns spyscope on clojars, we can continue to publish under the same artefact id. Otherwise, we'll change it to clj-commons/spyscope.

**Comment by randomizedthinking** [comment]
It sounds good. @dgrnbrg Can you add me to the maintainer of the project.

I think we can keep the artifact id for now... less interruption to users.

**Comment by slipset** [comment]
I've added you both as members of clj-commons. You should then be able to transfer spyscope to us.

**Comment by buzzdan** [comment]
Any updates on this issue?

**Comment by randomizedthinking** [comment]
@dgrnbrg Can you please add me as a collaborator to the original repository then I can transfer the repo to clj-commons? Or you can do the transfer by yourself.

**Comment by randomizedthinking** [comment]
Clone the repo at clj-commons. Since @dgrnbrg already agreed, and it requires no action from him assuming he is busy. Close the issue now.
