### ISSUE TITLE
Transfer some/all of pmonks' Clojure projects

### ISSUE THREAD

**Issue by pmonks** [clj-commons/wishlist#25]
I'd be more than happy to transfer some or all of [my Clojure projects](https://github.com/pmonks?utf8=%E2%9C%93&tab=repositories&q=&type=source&language=clojure) to `clj-commons`, if there's interest from the `clj-commons` team.  The most useful projects (imho) are these libraries:

* [`pmonks/CLJ-2253`](https://github.com/pmonks/CLJ-2253)
* [`pmonks/unfurl`](https://github.com/pmonks/unfurl)
* [`pmonks/multigrep`](https://github.com/pmonks/multigrep)
* [`pmonks/spinner`](https://github.com/pmonks/spinner)

For now I'm happy to continue maintaining everything, but am also keenly aware of the succession benefits of being part of a broader initiative.

**Comment by slipset** [comment]
I’ve invited you as a member of clj-commons, so feel free to transfer projects. I’ll set you as an admin on the projects once they’re transferred.

**Comment by pmonks** [comment]
Sadly, to transfer a repository you have to be an admin of both the source repo and the target _organisation_.

@slipset I'd be happy to make you an admin on each of the projects listed above, if you don't mind performing each of the transfers?  Alternatively you could temporarily make me an admin of `clj-commons`, I'll perform the transfers, then you can remove my admin role.

**Comment by pmonks** [comment]
Ok - all transfers are now in progress.

**Comment by pmonks** [comment]
@slipset once they're done, can you set me up as an admin on each of them, then close this issue?  Thanks!!

**Comment by slipset** [comment]
You should be admin now on your projects. Welcome to cli-commons :)

**Comment by pmonks** [comment]
Thanks!  😉
