### ISSUE TITLE
yesql

### ISSUE THREAD

**Issue by borkdude** [clj-commons/wishlist#3]
https://github.com/krisajenkins/yesql

**Comment by slipset** [comment]
I have a feeling this has been superseded by https://github.com/jkk/honeysql
Please close if you agree.

**Comment by borkdude** [comment]
Well, I proposed once to Kris to add something in the README that this lib has been superseded by HugSQL (https://hugsql.org). HoneySQL is a different beast. But there may be people still using yesql. Anyway, if they don't want it, I'm fine with it too :-).
