### ISSUE TITLE
flatland repos

### ISSUE THREAD

**Issue by royalaid** [clj-commons/wishlist#6]
Per https://github.com/circleci/clj-yaml/issues/22 it appears that flatland's repo's are unmaintained and would probably make sense inside clj-commons

**Comment by danielcompton** [comment]
I've sent Alan Malloy an email to see what he thinks.

**Comment by danielcompton** [comment]
I'm talking with Alan about this now, it was held up by me not responding over a holiday break.

**Comment by danielcompton** [comment]
https://github.com/clj-commons/useful
https://github.com/clj-commons/ordered
https://github.com/clj-commons/ring-gzip-middleware
https://github.com/clj-commons/ring-buffer

have all been transferred to CLJ Commons!
