### ISSUE TITLE
Marginalia

### ISSUE THREAD

**Issue by tsmacdonald** [clj-commons/wishlist#76]
[Marginalia](https://github.com/gdeer81/marginalia) was written by @fogus and [transferred](http://blog.fogus.me/2013/08/12/marginalia-has-a-new-home/) to @gdeer81 in 2013. Gary hasn't been active on Github or the Clojurians Slack for some time and the only commits since 2019 are two small PRs merged by @benjamin-bader.

There have been a few forks with minor improvements and a hard fork called [Sidenotes](https://github.com/captain-porcelain/sidenotes) that also appears to be unmaintained.

After [discussion on the Clojurians Slack](https://clojurians.slack.com/archives/C03S1KBA2/p1697109995570109), I'm proposing adoption by clj-commons and am willing to step up as a maintainer for a while (or until somebody else volunteers). Specific improvements I have in mind are:

* A new release with the several written-but-unreleased improvements that have been done since 2017

* Setting up CI

* Modernizing tests (one is failing, some use `is` without `deftest`, etc.)

* Upgrading the Clojure version, etc.

* Synthesizing the various forks and languishing PRs

* Issue triage

* _Some_ real feature work.  We're now [using Marginalia at Metabase](https://github.com/metabase/metabase/pull/34608) again (currently running off a fork I made/deployed), I've already encountered one bug related to reader tags, I'm feeling the pain of it reading lein's `project.clj` but not `deps.edn`, and I'm sure some other issues will come up too.

[I also filed an issue on the Marginalia repo itself](https://github.com/gdeer81/marginalia/issues/180) since I don't want to swipe the project out from under them if they have other plans.

**Comment by slipset** [comment]
I wouldn't mind. @seancorfield ?

**Comment by fogus** [comment]
I for one fully support this. I have lost touch with the project and Gary and can't say much about the outstanding issues, but will help however I can, time allowing.

**Comment by benjamin-bader** [comment]
I would be _thrilled_ to see the return of marginalia.

**Comment by slipset** [comment]
So given this, does anyone have any contact info on Gary, so we can try to contact him for a repo-transfer rather than a fork?

**Comment by seancorfield** [comment]
I'm definitely in favor of Marginalia moving to clj-commons. I've used it on a couple of internal projects some years ago and liked it.

**Comment by seancorfield** [comment]
I've reached out to @gdeer81 on LinkedIn. Will keep folks posted.

**Comment by tsmacdonald** [comment]
I take it there's been no response from Gary? Does @fogus happen to have admin access on the repo?

**Comment by seancorfield** [comment]
@tsmacdonald I doubt it since the repo was transferred from Fogus to Gary...

Per https://[clj-commons.org/accepting-projects.html](https://clj-commons.org/accepting-projects.html) we allow up to two months grace from the current owner before we fork so a little patience is needed 🙂

**Comment by fogus** [comment]
@tsmacdonald Alas, I do not have admin access.

**Comment by tsmacdonald** [comment]
No worries, I'll sit tight! And am not blocked on doing the actual coding :)

**Comment by seancorfield** [comment]
Gary just replied via LinkedIn and said he'll take a look at this tonight...

**Comment by seancorfield** [comment]
https://github.com/clj-commons/marginalia has been transferred into clj-commons. @tsmacdonald I'll add you to that repo.
