### ISSUE TITLE
Adopting metrics-clojure

### ISSUE THREAD

**Issue by ieugen** [clj-commons/wishlist#77]
We have discussed this on slack and https://github.com/metrics-clojure/metrics-clojure/issues/146 .

I am volunteering to do some maintenance:
- make code compatible with clj-commons
- migrate to deps.edn build (so we can use git deps)
- upgrade to latest metrics version

**Comment by seancorfield** [comment]
Big 👍 from me. We use this library at work.

**Comment by ieugen** [comment]
thanks @seancorfield . I will ask for review and we can plan the process if you like :) .

**Comment by slipset** [comment]
I've added @michaelklishin as a member here, so he should be able to transfer the repo

**Comment by ieugen** [comment]
I saw the project is now under clj-commons org. 
I think we can close this and continue with the adopting process on the project issue tracker. 
Please reopen if that is not the normal workflow.
