### ISSUE TITLE
Clooj

### ISSUE THREAD

**Issue by seancorfield** [clj-commons/wishlist#78]
https://github.com/eerohele/clooj -- clooj, a lightweight IDE for clojure

This might be a good on-ramp for beginners as it is zero-install (well, you need Java) and does the basics a Clojure editor needs without bells and whistles -- and it fits the bill of what Lee Spector has requested in order to teach his students.

Original repo, which no longer runs: https://github.com/arthuredelstein/clooj

**Comment by seancorfield** [comment]
The **develop** branch has the updated, working code in @eerohele repo.

**Comment by NoahTheDuke** [comment]
I volunteer to help maintain it.

**Comment by slipset** [comment]
LGTM. @seancorfield do you have any contact with @eerohele, or should I try to reach out for a transfer?

**Comment by seancorfield** [comment]
I created https://github.com/arthuredelstein/clooj/issues/131 on the original repo. If the original author doesn't respond, we can     transfer @eerohele fork instead.

**Comment by seancorfield** [comment]
Transferred in. Needs CODEOWNERS etc.
