### ISSUE TITLE
Adopt clj-yaml

### ISSUE THREAD

**Issue by slipset** [clj-commons/wishlist#9]
https://github.com/lancepantz/clj-yaml

**Comment by slipset** [comment]
I've sent Lance an email asking if he'd be interested in letting us adopt it.

**Comment by ikitommi** [comment]
There is https://github.com/circleci/clj-yaml too.

**Comment by slipset** [comment]
I'm aware of that, it was in fact @marcomorain from CircleCi who made me aware of this lib.

**Comment by marcomorain** [comment]
👍 on this. As long as we can have someone at CircleCI with commit bit on the repo, we 💯 support this.

**Comment by slipset** [comment]
Haven't heard anything from @lancepantz, so I guess the way forward would be to transfer https://github.com/circleci/clj-yaml, and publish the artifacts under `clj-commons`?

**Comment by slipset** [comment]
@marcomorain I've invited you to `clj-commons` so you should be able to transfer the repo

**Comment by marcomorain** [comment]
@slipset can you fork from `circleci/` into `clj-commons/`? If I want to transfer ownership of a repo under `circleci/` I'll have to do some unknown quantity of internal bureaucracy :)

**Comment by slipset** [comment]
Forked :)
